mod error;
mod matrix;
mod linear;
mod polynomial;
mod exponential;
mod timeseries;
mod kmeans;
mod knn;
mod logistic;
mod dbscan;
mod naive_bayes;
mod decision_tree;
mod pca;
mod perceptron;
mod random_forest;
mod silhouette;
mod confusion_matrix;
mod cross_validation;
mod data_split;
mod feature_importance;
mod standard_scaler;
mod gradient_boosting;
mod model_selection;
mod regression_metrics;
mod minmax_scaler;
mod robust_scaler;
mod normalizer;
mod label_encoder;
mod one_hot_encoder;
mod ordinal_encoder;
mod svm;
mod hierarchical;
mod clustering_metrics;
mod classification_metrics;
mod adaboost;
mod linear_regression;
mod kmeans_plus;
mod imputer;

use wasm_bindgen::prelude::*;
pub use error::MlError;

#[wasm_bindgen(start)]
pub fn init() {}

// Re-export all public types and functions
pub use linear::*;
pub use polynomial::*;
pub use exponential::*;
pub use timeseries::*;
pub use kmeans::*;
pub use knn::*;
pub use logistic::*;
pub use dbscan::*;
pub use naive_bayes::*;
pub use decision_tree::*;
pub use pca::*;
pub use perceptron::*;
pub use random_forest::*;
pub use silhouette::*;
pub use confusion_matrix::*;
pub use cross_validation::*;
pub use data_split::*;
pub use feature_importance::*;
pub use standard_scaler::*;
pub use gradient_boosting::*;
pub use model_selection::*;
pub use regression_metrics::*;
pub use minmax_scaler::*;
pub use robust_scaler::*;
pub use normalizer::*;
pub use label_encoder::*;
pub use one_hot_encoder::*;
pub use ordinal_encoder::*;
pub use svm::*;
pub use hierarchical::*;
pub use clustering_metrics::*;
pub use classification_metrics::*;
pub use adaboost::*;
pub use linear_regression::*;
pub use kmeans_plus::*;
pub use imputer::*;
